#!/bin/sh
#Discord TUI client

dir=$(mktemp -d /tmp/$(basename $0).XXXXXX)
cd $dir
cd $dir
wget https://gitlab.com/diamondburned/6cord/-/jobs/515405685/artifacts/raw/6cord_nk
chmod +x 6cord_nk
sudo ln -s $dir6cord_nk /usr/local/bin/6cord
