#!/bin/sh
# Install the aircrack suite from source

dir=$(mktemp -d /tmp/$(basename $0).XXXXXX)
cd $dir
git clone https://github.com/aircrack-ng/aircrack-ng.git
cd aircrack-ng
./autogen.sh
#./configure --with-experimental
./configure
sudo make  -j $(nproc) clean install
