#!/bin/bash
# Alacritty terminal emulator

doas apt-get install -y cmake libfreetype6-dev libfontconfig1-dev xclip libxcb-composite0-dev libx11-xcb-dev libxkbcommon-dev

git clone https://github.com/jwilm/alacritty
cd alacritty
cargo build -j $(nproc) --release
