#!/bin/sh

dir=$(mktemp -d /tmp/$(basename $0).XXXXXX)
cd $dir
doas apt install -y libxcb-icccm4-dev libxcb-ewmh-dev libxcb-keysyms1-dev
git clone https://github.com/baskerville/bspwm
cd bspwm
make -j $(nproc)
doas make -j $(nproc) install
