#!/bin/sh
# Cmatrix terminal bling

dir=$(mktemp -d /tmp/$(basename $0).XXXXXX)
cd $dir
git clone https://github.com/abishekvashok/cmatrix.git
cd cmatrix
autoreconf -i
./configure
sudo make -j $(nproc) clean install
