#!/bin/sh

if [ -z $(command -v emacs) ]; then
	echo "Emacs needs to be installed to continue. Exiting"
	exit
fi

git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom -y install
doom sync
