#!/bin/sh
dir=$(mktemp -d /tmp/$(basename $0).XXXXXX)
cd $dir
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
doas apt install ./google-chrome-stable_current_amd64.deb
doas apt install google-chrome-stable 
