#!/bin/sh

#cd /opt
#git clone https://www.github.com/Airblader/i3 i3-gaps
#cd i3-gaps
#mkdir -p build && cd build
#meson ..
#ninja
#sudo meson install

cd /opt
git clone https://www.github.com/Airblader/i3 i3-gaps
cd i3-gaps
git checkout gaps && git pull
autoreconf --force --install
rm -rf build
mkdir build
cd build
meson ..
ninja
sudo meson install
