#!/bin/sh

#cd $dir
#git clone https://www.github.com/Airblader/i3 i3-gaps
#cd i3-gaps
#mkdir -p build && cd build
#meson ..
#ninja
#sudo meson install

dir=$(mktemp -d $(basename $0).XXXXXX)
cd $dir
git clone https://www.github.com/Airblader/i3 i3-gaps
cd i3-gaps
git checkout gaps && git pull
autoreconf --force --install
rm -rf build
mkdir build
cd build
meson ..
ninja
sudo meson install
