#!/bin/sh
# Install LF file manager binary

dir=$(mktemp -d $(basename $0).XXXXXX)
cd $dir

case "$(arch)" in
	x86_64) wget https://github.com/gokcehan/lf/releases/download/r16/lf-linux-amd64.tar.gz;;
	i386|i486|i586|i686) wget https://github.com/gokcehan/lf/releases/download/r16/lf-linux-386.tar.gz;;
	arm64) wget https://github.com/gokcehan/lf/releases/download/r16/lf-linux-arm64.tar.gz;;
esac

sudo tar -xzvf lf-linux-*.tar.gz -C /usr/local/bin/
