#!/bin/sh

git clone --depth 1 https://gitlab.manjaro.org/tsys/linux-pinebook-pro.git /opt/linux-pinebook
cd /opt/linux-pinebook
make menuconfig
make ARCH=$(arch) CROSS_COMPILE=aarch64-linux-gnu- -j $(nproc)
