#!/bin/sh

echo "deb http://download.opensuse.org/repositories/home:/strycore/Debian_10/ ./" | doas tee /etc/apt/sources.list.d/lutris.list
wget -q https://download.opensuse.org/repositories/home:/strycore/Debian_10/Release.key -O- | doas apt-key add -
doas apt update
doas apt install lutris -y
