#!/bin/sh
# Compile neovim from source

dir=$(mktemp -d /tmp/$(basename $0).XXXXXX)
cd $dir
git clone --depth=1 https://github.com/neovim/neovim.git
cd neovim
make -j 1 CMAKE_INSTALL_PREFIX=/usr/local/bin/
doas make install
