#!/bin/sh
# Compile neovim from source

dir=$(mktemp -d $(basename $0).XXXXXX)
cd $dir
git clone https://github.com/neovim/neovim.git
cd neovim
make -j 1 CMAKE_INSTALL_PREFIX=/usr/local/bin/
sudo make install
