#!/bin/sh

dir=$(mktemp -d $(basename $0).XXXXXX)
cd $dir
case $(arch) in
	x86_64)
		wget https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u275-b01/OpenJDK8U-jdk_x64_linux_hotspot_8u275b01.tar.gz
		tar -xzvf OpenJDK8U-jdk_x64_linux_hotspot_8u275b01.tar.gz
		mv jdk8* jdk
		;;
	aarch64)
		wget https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u275-b01/OpenJDK8U-jdk_aarch64_linux_hotspot_8u275b01.tar.gz
		tar -xzvf OpenJDK8U-jdk_aarch64_linux_hotspot_8u275b01.tar.gz
		mv jdk8* jdk
		;;
esac
