#!/bin/sh

dir=$(mktemp -d /tmp/$(basename $0).XXXXXX)
cd $dir
git clone https://github.com/yshui/picom.git
cd $dir/picom
git submodule update --init --recursive
meson --buildtype=release . build
doas ninja -C build install
