#!/bin/sh

dir=$(mktemp -d /tmp/$(basename $0).XXXXXX)
cd $dir
git clone https://github.com/ibhagwan/picom.git $dirpicom-ibhagwan
cd $dir/picom-ibhagwan
git submodule update --init --recursive
meson --buildtype=release . build
sudo ninja -C build install
