#!/bin/sh

dir=$(mktemp -d /tmp/$(basename $0).XXXXXX)
cd $dir
git clone https://github.com/jonaburg/picom
cd picom
meson --buildtype=release . build
# To install the binaries in /usr/local/bin (optional)
doas ninja -C build install
