#!/bin/sh

dir=$(mktemp -d /tmp/$(basename $0).XXXXXX)
cd $dir
git clone https://github.com/adi1090x/polybar-themes
cd polybar-themes/polybar-1
cp -r fonts/* ~/.local/share/fonts
fc-cache -v
doas rm /etc/fonts/conf.d/70-no-bitmaps.conf
#cp -r * ~/.config/polybar
