#!/bin/sh
# Suckless presentation thing

# libpng libjpeg-turbo
dir=$(mktemp -d /tmp/$(basename $0).XXXXXX)
cd $dir
git clone https://git.suckless.org/farbfeld
cd farbfeld
make clean
make
doas make install

# Xlib Xft farbfeld
dir=$(mktemp -d /tmp/$(basename $0).XXXXXX)
cd $dir
git clone https://git.suckless.org/sent
cd sent
make
doas make install
