#!/bin/sh

dir=$(mktemp -d /tmp/$(basename $0).XXXXXX)
cd $dir
git clone https://github.com/thestinger/vte-ng.git
cd vte-ng
./autogen.sh
sudo make install

git clone --recursive https://github.com/thestinger/termite.git
cd termite
sudo make install
