#!/bin/sh
# Installs tty-clock. A cli clock
# Dependencies: ncurses-devel (fedora)

dir=$(mktemp -d /tmp/$(basename $0).XXXXXX)
cd $dir
git clone https://github.com/xorg62/tty-clock.git
cd tty-clock
sudo make -j $(nproc) clean install
