#!/bin/sh
# Kali linux undercover mode all distros

dir=$(mktemp -d /tmp/$(basename $0).XXXXXX)
cd $dir
git clone https://github.com/SofianeHamlaoui/Go-undercover && cd Go-undercover
chmod +x ./install.sh
sudo ./install.sh
