#!/bin/sh
#https://github.com/ungoogled-software/ungoogled-chromium-debian
# Branch list
#origin/HEAD -> origin/debian_sid
#origin/debian_buster
#origin/debian_sid
#origin/ubuntu_bionic
#origin/ubuntu_focal
#origin/ungoogled_debian_minimal
#origin/unportable

cd /opt/
git clone --recurse-submodules https://github.com/ungoogled-software/ungoogled-chromium-debian.git
cd ungoogled-chromium-debian
git checkout --recurse-submodules "$1"
cp -r debian build/src
./debian/scripts/setup debian
sudo mk-build-deps -i debian/control
rm ungoogled-chromium-build-deps_*
./debian/scripts/setup local-src
dpkg-buildpackage -b -uc

#If the build aborts during the last command, it can be restarted with this command:
#dpkg-buildpackage -b -uc -nc
#If it still fails, then try this command (this will clear any intermediate build outputs):
#dpkg-buildpackage -b -uc
