#!/bin/sh
# Unshortens urls

if [ -z "$(command -v npm)" ]; then
	echo "Npm is a required dependency. Exiting"
	exit
fi

dir=$(mktemp -d /tmp/$(basename $0).XXXXXX)
cd $dir
git clone https://github.com/amrwc/unshorten-url.git
cd unshorten-url
npm install
sudo mv unshorten-url.js /usr/local/bin/
sudo chmod 555 /usr/local/bin/unshorten-url.js
