#!/bin/sh
# It's some kernel module to get virtual a webcam going

# Installing linux kernel headers for current running kernel
doas apt install -y linux-headers-$(uname -r)

dir=$(mktemp -d /tmp/$(basename $0).XXXXXX)
cd $dir
git clone https://github.com/umlaeute/v4l2loopback.git
cd v4l2loopback
doas make 
doas make install
doas cp v4l2loopback.ko /lib/modules/$(uname -r)
doas depmod -a
doas modprobe v4l2loopback
