#!/bin/sh

if [ ! -z $(command -v youtube-dl) ]; then
	echo "Youtube-dl already in path. Please remove it before installing"
	exit
fi

sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl
