#!/bin/sh
# Install H264 codecs for chromium, firefox, and vivaldi
# Chromium freeworld should replace the chromium-browser package
# For vivaldi
# sudo dnf install chromium-libs-media-freeworld
# sudo cp -av /usr/lib64/chromium-browser/libffmpeg.so /opt/vivaldi/lib/

sudo dnf install chromium-freeworld compat-ffmpeg28 ffmpeg-libs -y
